### ISSUE TITLE
Migrate unit tests from tape to jest

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-geocoder#63]
We have migrated all unit tests in MapLibre GL JS from tap/tape to jest. I think it would make sense to do the same here. 

Relevant issue in GL JS: 

https://github.com/maplibre/maplibre-gl-js/issues/273

**Comment by HarelM** [comment]
I've just looked into it, since the tests are using the browser it would require to mock everything as we do for maplibre-gl-js, which is a high price to pay.
I've looked at using Puppeteer, but then you need to covert all the logic that runs in the test to be executed with `evaluate` which is also a hassle.
Bottom line, for some reason, I can't find an easy solution to this... :-/
